export const TRANSLATIONS = {
  English: {
      "Username": 'Username',
      "Password": 'Password',
      "ConfirmPassword": 'ConfirmPassword',
      "Forgot_password": 'Forgot password?',
      "Sign_in": 'Login',
      "Orders": 'Orders',
      "Dashboard": 'Dashboard',
      "Sales_No": 'Sales No',
      "Previous":'Previous',
      "Next":'Next',
      "Show_entries":'Show entries',
      "Show":'Show',
      "Entries":'entries',
      "Show_page":'Showing page',
      "PO_No": 'PO_No',
      "Order_Date": 'OrderDate',
      "Shipping_Date": "ShippingDate",
      "Total": 'Total',
      "Currency": 'Currency',
      "Status": 'Status',
      "Download": 'Download',
      "Past_Due": 'Past Due',
      "Due_Soon": 'Due Soon',
      "Total_Outstanding": 'Total Outstanding',
      "Place_an_order": 'Place an order',
      "Search_Lines": 'Search Products and Create Order Lines',
      "Make_a_Payment": 'Make a Payment',
      "Credit_card": 'Credit card, PayPal, Worldpay, On Account',
      "Last_5_Orders": 'Last 5 Orders',
      "Next_5_Deliveries_Due": 'Next 5 Deliveries Due',
      "Outstanding_Payments": 'Outstanding Payments',
      "Sales_Number": 'Sales Number',
      "Delivery_Number": 'Delivery Number',
      "Due_Date": 'Due Date',
      "Invoice_Number": 'Invoice Number',
      "Amount": 'Amount',
      "Enter_email": 'EnterEmail',
      "Back_to_Sign_in": 'Back to Sign in',
      "Next_Step": 'Next Step',
      "New_Password": 'NewPassword',
      "Confirm_Password": 'ConfirmPassword',
      "Item_Name": 'ItemName',
      "Description": 'Description',
      "Quantity": 'Quantity',
      "Shipped_Quantity": 'ShippedQuantity',
      "Price": 'Price',
      "Requested_Delivery_Date": 'Requested Delivery Date',
      "PO_Reference": 'PO Reference',
      "Billing_Address": 'Billing Address',
      "Shipping_Address": 'Shipping Address',
      "Order_Comments": 'Order Comments',
      "Product": 'Product',
      "Item_Price": 'ItemPrice',
      "Line_Total": 'Line Total',
      "Click_to_make_new_row": 'Click to make new row',
      "Search": 'Search',
      "Submit_Order": 'Submit Order',
      "Make_a_payment": 'Make a payment',
      "Make_Payment": 'Make Payment',
      "Play": 'Play',
      "Type": 'Type',
      "Documet_Date": 'DocumentDate',
      "Invoice_No": 'Invoice No',
      "Business_partner": 'Business partner',
      "Contact": 'Contact',
      "Ordertype": 'Ordertype',
      "Unit": 'Unit',
      "Delivery": 'Delivery #',
      "DeliveryDate": 'DeliveryDate',
      "Pay": 'Pay',
      "Collection": 'Collection',
      "Your_order_reference": 'Your order reference',
      "Invoice": 'Invoice',
      "Invoice #": 'Invoice #',
      "InvoiceDate": 'InvoiceDate',
      "OrderNumber": 'OrderNumber',
      "Batch": 'Batch',
      "Invoices": 'Invoices',
      "CreditNotNo": 'Credit Note NO',
      "DateCreated": 'Date Created',
      "Balance": 'Balance',
      "Applied_by": 'Applied by',
      "Place_sample_order": 'Place sample order',
      "Save": 'Save',
      "Collection_or_historical_orders": 'Collection or historical orders',
      "Action": 'Action',
      "Product_code": 'Product code',
      "Jobs": 'Jobs',
      "Length_specified": 'Length specified',
      "Length_calculated": 'Length calculated',
      "Pattern": 'Pattern',
      "Order_rule": 'Order Rule',
      "Add_stroke": 'Add stroke',
      "Remove_stroke": 'Remove stroke',
      "Calculate_pattern_length": 'Calculate pattern length',
      "Processing": 'Processing',
      "Cancel": 'Cancel',
      "Verspringend": 'verspringend',
      "Accept_delivery": 'Accept Delivery',
      "No_partial_deliveries": 'No partial deliveries',
      "Go_back_to_the_order": 'Go back to the order',
      "Resume": 'Resume',
      "Allowance": 'Allowance',
      "Product_image": 'Product image',
      "Email": 'Email',
      "Sign_up": 'Sign up',
      "have_an_account": "Don't have an account?",
      "User": 'User',
      "Users": 'Users',
      "Add_User": 'Add User',
      "UserName": 'UserName',
      "PhoneNumber": 'PhoneNumber',
      "Active": 'Active',
      "Result_on_page": 'result on page',
      "Results_of": 'results of',
      "Delete": 'Delete',
      "Edit": 'Edit',
      "Roles": 'Role',
      "UserCode": 'UserCode',
      "CustomerCode": 'CustomerCode',
      "FirstName": 'FirstName',
      "LastName": 'LastName',
      "keep_logged_in": 'Keep me logged in',
      "have_account": "Don't have account",
      "Add_order": 'Add Order',
      "ItemCode": 'ItemCode',
      "ItemDescription": 'ItemDescription',
      "DocNum": 'DocNum',
      "DocDate": 'DocDate',
      "cardName": 'cardName',
      "dbsCollection": 'dbsCollection',
      "Filter": 'Filter',
      "Quick_search": 'Quick_search',
      "Add_filter": 'Add filter',
      "Deliveries": 'Deliveries',
      "Salesinvoices": 'Salesinvoices',
      "DocTotal": 'DocTotal',
      "Deactivate": 'Deactivate',
      "Returns": 'Returns',
      "Edit_User": 'Edit User',
      "Test": 'Test',
      "Login As": 'Login As',
      "Go_Back_Admin": 'GoBackAdmin',
      "Customer_reference": 'Customer Reference',
      "City_Country": 'City,Country',
      "Street": 'Street',
      "Product_description": 'Product description',
      "Image": "Image",
      "Expected_deliver_week": "Expected delivery week",
      "Order": 'Order #',
      "Language": 'Language',
      "Search_Item": 'Search Item',
      "Add_to_order": 'Add to order',
      "Orderline": 'Orderline',
      "Staggered": 'Staggered',
      "Rows": 'Rows',
      "Row_length": 'Row length',
      "Row_length_calculated": 'Row length calculated',
      "Total_row_length": 'Total row length',
      "Total_lengh": 'Total length',
      "Add_to_row": 'Add to row',
      "Pattern_calculation": 'Pattern calculation',
      "Date": 'Date',
      "DocDueDate": 'DocDueDate',
      "OrderSummary": 'Order Summary',
      "Profile": 'Profile',
      "ResetPassword": 'ResetPassword',
      "Logout": 'Logout',
      "CustomerName": 'CustomerName',
      "ShowPrice": 'ShowPrice',
      "Return details": 'Return details',
      "Salesinvoice details": 'Salesinvoice details',
      "Delivery details": 'Delivery details',
      "NoPatternCalculation": 'NoPattern Calculation',
      "Pattern calculation needs to be filled for this product, do you want to delete the product from the order lines?": 'Pattern calculation needs to be filled for this product, do you want to delete the product from the order lines?',
      "Zipcode": "Zipcode",
      "City": "City",
      "StreetNo": "StreetNo",
      "News": "News",
      "Add News": "Add News",
      "Subject Dutch": "Subject Dutch",
      "Subject English": "Subject English",
      "Subject German": "Subject German",
      "Subject French": "Subject French",
      "Text Dutch": "Text Dutch",
      "Text English": "Text English",
      "Text German": "Text German",
      "Text French": "Text French",
      "StartDate": "StartDate",
      "EndDate": "EndDate",
      "Are you sure to do this?": "Are you sure to do this?",
      "View": "View",
      "Edit News": "Edit News",
      "View News": "View News",
      "Are you sure that you want to return this item?": "Are you sure that you want to return this item?",
      "Approve order": "Approve order",
      "I agree with the Terms and Conditions": "I agree with the Terms and Conditions",
      "No partial deliveries": "No partial deliveries",
      "Return #": 'Return #',
      "ReturnDate": 'ReturnDate'
    },

    Dutch: {
      "Username": 'Gebruikersnaam',
      "Password": 'Wachtwoord',
      "ConfirmPassword": 'Bevestig wachtwoord',
      "Forgot_password": 'Wachtwoord vergeten?',
      "Sign_in": 'Aanmelden',
      "Orders": 'Vestellen',
      "Dashboard": 'Dashboard',
      "Sales_No": 'Verkoop No',
      "Previous":'Vorige',
      "Next":'Volgende',
      "Show_entries":'Toon records',
      "Show":'Toon',
      "Entries":'Records',
      "Show_page":'Pagina weergeven',
      "PO_No": 'PO_No',
      "Order_Date": 'BestellenDatum',
      "Shipping_Date": 'VerzendingDatum',
      "Total": 'Totaal',
      "Currency": 'Valuta',
      "Status": 'Toestand',
      "Download": 'Download',
      "Past_Due": 'Verleden Due',
      "Due_Soon": 'Due Spoedig',
      "Total_Outstanding": 'Totaal Voortreffelijk',
      "Place_an_order": 'Een bestelling plaatsen',
      "Search_Lines": 'Zoek producten en maak orderregels',
      "Make_a_Payment": 'Maak een betaling',
      "Credit_card": 'Creditcard, PayPal, Worldpay, op account',
      "Last_5_Orders": 'Laatste 5 bestellingen',
      "Next_5_Deliveries_Due": 'Volgende 5 Leveringen verschuldigd',
      "Outstanding_Payments": 'Openstaande betalingen',
      "Sales_Number": 'Verkoop Aantal',
      "Delivery_Number": 'Levering Aantal',
      "Due_Date": 'Due Datum',
      "Invoice_Number": 'Factuur Aantal',
      "Amount": 'Bedrag',
      "Enter_email": 'InvoerenEmail',
      "Back_to_Sign_in": 'Terug naar inloggen',
      "Next_Step": 'Volgende Stap',
      "New_Password": 'Nieuw Wachtwoord',
      "Confirm_Password": 'Bevestigen Wachtwoord',
      "Item_Name": 'ItemNaam',
      "Description": 'Beschrijving',
      "Quantity": 'Aantal',
      "Shipped_Quantity": 'Verunden Aantal',
      "Price": 'Prijs',
      "Requested_Delivery_Date": 'Gevraagde afleverdatum',
      "PO_Reference": 'Po Referenie',
      "Billing_Address": 'Factuur Adres',
      "Shipping_Address": 'Verzending  Adres',
      "Order_Comments": 'Bestellen Comments',
      "Product": 'Product',
      "Item_Price": 'ItemPrijs',
      "Line_Total": 'Lijn Totaal',
      "Click_to_make_new_row": 'Click om een ​​nieuwe rij te maken',
      "Search": 'Zoeken',
      "Submit_Order": 'Voorleggen Bestellen',
      "Make_a_payment": 'Maken een betaling',
      "Make_Payment": 'Maken Betaling',
      "Play": 'Speel',
      "Type": 'Type',
      "Documet_Date": 'DocumentDatum',
      "Invoice_No": 'Factuur No',
      "Business_partner": 'Bedrijf partner',
      "Contact": 'Contact',
      "Ordertype": 'Bestellentype',
      "Unit": 'Eenheid',
      "Delivery": 'Levering #',
      "DeliveryDate": 'LeveringDatum',
      "Pay": 'Betalen',
      "Collection": 'Verzameling',
      "Your_order_reference": 'Votre reférence de commande',
      "Invoice": 'Factuur',
      "Invoice #": 'Factuur #',
      "InvoiceDate": 'FactuurDatum',
      "OrderNumber": 'BestellenNummer',
      "Batch": 'Partij',
      "Invoices": 'Facturen',
      "CreditNotNo": 'Credit Niet Nee',
      "DateCreated": 'Datum gemaakt',
      "Balance": 'Balance',
      "Applied_by": 'Aangebracht door',
      "Place_sample_order": 'Plaats monster bestelling',
      "Save": 'Obslaan',
      "Collection_or_historical_orders": 'Verzameling of historische bestellingen',
      "Action": 'Actie',
      "Product_code": 'Product code',
      "Jobs": 'Banen',
      "Length_specified": 'Lengte opgegeven',
      "Length_calculated": 'Lengte berekend',
      "Pattern": 'Patrron',
      "Order_rule": 'Orderrege',
      "Add_stroke": 'Toevoegen  beroerte',
      "Remove_stroke": 'Verwijderen beroerte',
      "Calculate_pattern_length": 'Bereken patroonlengte',
      "Processing": 'Verwerken',
      "Cancel": 'Annuleren',
      "Verspringend": 'Verspringend',
      "Accept_delivery": 'Levering accepteren',
      "No_partial_deliveries": 'Geen gedeeltelijke leveringen',
      "Go_back_to_the_order": 'Ga terug naar de bestelling',
      "Resume": 'Hervat',
      "Allowance": 'Toelage',
      "Product_image": 'Product afbeelding',
      "Email": 'E-mail',
      "Sign_up": 'Inschrijven',
      "have_an_account": "Heb je geen account?",
      "User": 'Gebruiker',
      "Users": 'Gebruikers',
      "Add_User": 'Voeg gebruiker toe',
      "UserName": 'Gebruikersnaam',
      "PhoneNumber": 'Telefoonnummer',
      "Active": 'Actief',
      "Result_on_page": 'Resultaten op pagine',
      "Results_of": 'resultaten van',
      "Delete": 'Verwijderen',
      "Edit": 'Bewerk',
      "Role": 'Rol',
      "UserCode": 'GebruikerCode',
      "CustomerCode": 'klantCode',
      "FirstName": 'EersteNaam',
      "LastName": 'LaatsteName',
      "keep_logged_in": 'Ik wil ingelogd blijven',
      "have_account": "Heb geen account",
      "Add_order": 'Toevoegen Bestellen',
      "ItemCode": 'Artikelcode',
      "ItemDescription": 'ItemBeschrijving',
      "DocNum": 'DocNum',
      "DocDate": 'DocDatum',
      "cardName": 'kaartNaam',
      "dbsCollection": 'dbsCollectie',
      "Filter": 'Filter',
      "Quick_search": 'Snel zoeken',
      "Add_filter": 'Toevoegen filter',
      "Deliveries": 'Leveringen',
      "Salesinvoices": 'Verkoopfacturen',
      "DocTotal": 'DocTotaal',
      "Deactive": 'deactiveren',
      "Returns": 'Geeftterug',
      "Edit_User": 'Bewerk Gebruiker',
      "Test": 'Test1111',
      "Login As": 'Login As',
      "Go_Back_Admin": 'GoBackAdmin',
      "Customer_reference": 'Klantr referentie',
      "City_Country": 'Stad,Land',
      "Street": 'straat',
      "Product_description": 'Product beschrijving',
      "Image": 'beeld',
      "Expected_deliver_week" : 'Verwacht levering week',
      "Order": 'Bestellen#',
      "Language": 'Taal',
      "Search_Item": 'Item zoeken',
      "Add_to_order": 'Toevoegen aan bestelling',
      "Orderline": 'Orderregel',
      "Staggered": 'Wankelend',
      "Rows": 'Rijen',
      "Row_length": 'Rij lengte',
      "Row_length_calculated": 'Rij lengte berekend',
      "Total_row_length": 'Totaal rij lengte',
      "Total_lengh": 'Totaal lengte',
      "Add_to_row": 'Toevoegen aan rij',
      "Pattern_calculation": 'Patroonberekening',
      "Date": 'Datum',
      "DocDueDate": 'DocTengevolgeDatum',
      "OrderSummary": 'Bestellen Overzicht',
      "Profile": 'Profiel',
      "ResetPassword": 'ResetWachtwoord',
      "Logout": 'Uitloggen',
      "CustomerName": 'Klantnaam',
      "ShowPrice": 'Prijs Laten zien',
      "Return details": 'Details retourneren',
      "Salesinvoice details": 'Verkoopfactuurgegevens',
      "Delivery details": 'Verzendgegevens',
      "NoPatternCalculation": 'Geen patroonberekening',
      "Pattern calculation needs to be filled for this product, do you want to delete the product from the order lines?": "Patroonberekening moet worden ingevuld voor dit product, wilt u het product uit de orderregels verwijderen?",
      "Zipcode": "Zipcode",
      "City": "Stad",
      "StreetNo": 'StraatNr',
      "News": "Nieuws",
      "Add News": "Nieuws Toevoegen",
      "Subject Dutch": "Onderwerpen Nederlands",
      "Subject English": "Onderwerp Engels",
      "Subject German": "Onderwerp Duits",
      "Subject French": "Onderwerp Frans",
      "Text Dutch": "Tekst Nederlands",
      "Text English": "Tekst Engels",
      "Text German": "Tekst Duits",
      "Text French": 'Tekst Frans',
      "StartDate": "StartDatum",
      "EndDate": "EindDatum",
      "Are you sure to do this?": "Weet je het zeker?",
      "View": "Visie",
      "Edit News": "Nieuws Bewerken",
      "View News": "Bekijk Nieuws",
      "Are you sure that you want to return this item?": "Weet u zeker dat u dit artikel wilt retourneren?",
      "Approve order": "Bestelling goedkeuren",
      "I agree with the Terms and Conditions": "Ik ga akkoord met de algemene voorwaarden",
      "No partial deliveries": "Geen deelleveringen",
      "Return #": 'Return #',
      "ReturnDate": 'ReturnDate'
    }, 
    
    German: {
      "Username": 'Nutzername',
      "Password": 'Passwort',
      "ConfirmPassword": 'Bevestig wachtwoord',
      "Forgot_password": 'Vergessen Passwort',
      "Sign_in": 'Einloggen',
      "Orders": 'Aufträge',
      "Dashboard": 'Instrumententafel',
      "Sales_No": 'Vertrieb Nein',
      "Previous":'Bisherige',
      "Next":'Nächster',
      "Show_entries":'Show Einträge',
      "Show":'Show',
      "Entries":'Einträge',
      "Show_page":'Show Seite',
      "PO_No": 'PO_No',
      "Order_Date": 'Bestellung Date',
      "Shipping_Date": 'Versand Date',
      "Total": 'Gesamt',
      "Currency": 'Währung',
      "Status": 'Status',
      "Download": 'Herunterladen',
      "Past_Due": 'Vergangenheit Fällig',
      "Due_Soon": 'Fällig Bald',
      "Total_Outstanding": 'Gesamt Hervorragend',
      "Place_an_order": 'Ort ein bestellen',
      "Search_Lines": 'Suche Linien',
      "Make_a_Payment": 'Machen ein Zahlung',
      "Credit_card": 'Anerkennung Karte',
      "Last_5_Orders": 'Zuletzt 5 Aufträge',
      "Next_5_Deliveries_Due": 'Nächster 5 Lieferungen Fällig',
      "Outstanding_Payments": 'Hervorragend Zahlungen',
      "Sales_Number": 'Der Umsatz Nummer',
      "Delivery_Number": 'Lieferung Nummer',
      "Due_Date": 'Fällig Datum',
      "Invoice_Number": 'Rechnung Nummer',
      "Amount": 'Menge',
      "Enter_email": 'Eingeben Email',
      "Back_to_Sign_in": 'Zurück zu Zeichen ',
      "Next_Step": 'Nächster Schritt',
      "New_Password": 'Neu Passwort',
      "Confirm_Password": 'Bestätigen Passwort',
      "Item_Name": 'Article Name',
      "Description": 'Beschreibung',
      "Quantity": 'Menge',
      "Shipped_Quantity": 'Versand erfolgt Menge',
      "Price": 'Preis',
      "Requested_Delivery_Date": 'Angefordert Lieferung Datum',
      "PO_Reference": 'Po Referenz',
      "Billing_Address": 'Abrechnung Addresses',
      "Shipping_Address": 'Versand Addresses',
      "Order_Comments": 'Bestellung Bemerkungen',
      "Product": 'Product',
      "Item_Price": 'Item Preis',
      "Line_Total": 'Linie Gesamt',
      "Click_to_make_new_row": 'Klicken zu machen Neu Reihe',
      "Search": 'Suche',
      "Submit_Order": 'Einreichen  Bestellung',
      "Make_a_payment": 'Machen ein Zahlung',
      "Make_Payment": 'Machen Zahlung',
      "Play": 'Abspielen',
      "Type": 'Art',
      "Documet_Date": 'Dokumentieren Datum',
      "Invoice_No": 'Rechnung Nein',
      "Business_partner": 'Geschäft Partner',
      "Contact": 'Kontakt',
      "Ordertype": 'Auftragsart',
      "Unit": 'Einheit',
      "Delivery": 'Lieferung #',
      "DeliveryDate": 'LieferungDatum',
      "Pay": 'Zahlen',
      "Collection": 'Sammlung',
      "Your_order_reference": 'Ihre Bestellnummer',
      "Invoice": 'Rechnung',
      "Invoice #": 'Rechnung #',
      "InvoiceDate": 'RechnungDatum',
      "OrderNumber": 'BestellungNummer',
      "Batch": 'Stapel',
      "Invoices": 'Rechnungen',
      "CreditNotNo": 'Anerkennung Nicht Nein',
      "DateCreated": 'Date erstellt',
      "Balance": 'Balance',
      "Applied_by": 'Durch Anwendung',
      "Place_sample_order": "Passer la commande d'échantillon",
      "Save": 'Speichern',
      "Collection_or_historical_orders": 'Sammlung oder historische Ordnungen',
      "Action": 'Aktion',
      "Product_code": 'Product code',
      "Jobs": 'Arbeitsplätze',
      "Length_specified": 'Länge angegeben',
      "Length_calculated": 'Länge berechnet',
      "Pattern": 'Muster',
      "Order_rule": 'Bestellregel',
      "Add_stroke": 'Strich hinzufügen',
      "Remove_stroke": 'Hub entfernen',
      "Calculate_pattern_length": 'Berechnen Sie die Musterlänge',
      "Processing": 'Wird bearbeitet',
      "Cancel": 'Stornieren',
      "Verspringend": 'Verspringend',
      "Accept_delivery": 'Lieferung annehmen',
      "No_partial_deliveries": 'Keine Teillieferungen',
      "Go_back_to_the_order": 'Gehen Sie zurück zur Bestellung',
      "Resume": 'Weitermachen',
      "Allowance": 'Beihilfe',
      "Product_image": 'Produktbild',
      "Email": 'Email',
      "Sign_up": 'Anmelden',
      "have_an_account": 'Sie haben noch keinen Account?',
      "User": 'Nutzer',
      "Users": 'Benutzer',
      "Add_User": 'Nutzer hinzufügen',
      "UserName": 'Nutzername',
      "PhoneNumber": 'Telefonnummer',
      "Active": 'Aktiv',
      "Result_on_page": 'Ergebnis auf Seite',
      "Results_of": 'Ergebnisse von',
      "Delete": 'Löschen',
      "Edit": 'Bearbeiten',
      "Roles": 'Rollen',
      "UserCode": 'Benutzercode',
      "CustomerCode": 'Kundencode',
      "FirstName": 'Vorname',
      "LastName": 'Nachname',
      "keep_logged_in": 'Lass mich angemeldet',
      "have_account": 'Ich habe kein Konto',
      "Add_order": 'Bestellung hinzufügen',
      "ItemCode": 'ArtikelCode',
      "ItemDescription": 'ArtikelBeschreibung',
      "DocNum": 'DocNum',
      "DocDate": 'DocDatum',
      "cardName": 'KarteName',
      "dbsCollection": 'dbsSammlung',
      "Filter": 'Filter',
      "Quick_search": 'Schnell Suche',
      "Add_filter": 'HinzufügenFilter',
      "Deliveries": 'Lieferungen',
      "Salesinvoices": 'Verkaufsrechnungen',
      "DocTotal": 'DocGesamt',
      "Deactivate": 'DeaktivierenSie',
      "Returns": 'Kehrt zurück',
      "Edit_User": 'Bearbeiten Nutzer',
      "Test": 'Prüfung',
      "Login As": 'Anmelden als',
      "Go_Back_Admin": 'Gehe zurück Admin',
      "Customer_reference": 'Kunde Referenz',
      "City_Country": 'Stadt Land',
      "Street": 'Straße',
      "Product_description": 'Produkt Beschreibung',
      "Image": 'Bild',
      "Expected_deliver_week": 'Voraussichtliche Lieferwoche',
      "Order": 'Bestellen #',
      "Language": 'Sprache',
      "Search_Item": 'Artikel suchen',
      "Add_to_order": 'Zur Bestellung hinzufügen',
      "Orderline": 'Bestelllinie',
      "Staggered": 'Gestaffelt',
      "Rows": 'Reihen',
      "Row_length": 'Zeilenlänge',
      "Row_length_calculated": 'Reihe long berechnet',
      "Total_row_length": 'Gesamt Reihe Länge',
      "Total_lengh": 'Gesamt Länge',
      "Add_to_row": 'Zur Zeile hinzufügen',
      "Pattern_calculation": 'Musterberechnung',
      "Date": 'Datum',
      "DocDueDate": 'DocFälligDatum',
      "OrderSummary": 'Auftrag Zusammenfassung',
      'Profile': 'Profil',
      "ResetPassword": 'ZurücksetzenPasswort',
      "Logout": 'Ausloggen',
      "CustomerName": 'Kundenname',
      "ShowPrice": 'PreisAnzeigen',
      "Return details": 'Details zurückgeben',
      "Salesinvoice details": 'Details zur Verkaufsrechnung',
      "Delivery details": 'Lieferdetails',
      "NoPatternCalculation": 'Keine Musterberechnung',
      "Patroonberekening moet worden ingevuld voor dit product, wilt u het product uit de orderregels verwijderen?": "Die Musterberechnung muss für dieses Produkt ausgefüllt werden. Möchten Sie das Produkt aus den Bestellpositionen löschen?",
      "Zipcode": "Zipcode",
      "City": "Stadt",
      "StreetNo": "StraßeNein",
      "News": "Nachrichten",
      "Add News": "Nachrichten Hinzufügen",
      "Subject Dutch": 'Fach Niederländisch',
      "Subject English": "Fach Englisch",
      "Subject German": "Fach Deutsch",
      "Subject French": "Fach Französisch",
      "Text Dutch": "Text Nederlands",
      "Text English": "Text Engels",
      "Text German": "Text Duits",
      "Text French": 'Text Frans',
      "StartDate": "AnfangsDatum",
      "EndDate": "EndeDatum",
      "Are you sure to do this?": "Bist du sicher das zu tun?",
      "View": "Aussicht",
      "Edit News": "Nachrichten Bearbeiten",
      "View News": "Nachrichten Anzeigen",
      "Are you sure that you want to return this item?": "Sind Sie sicher, dass Sie diesen Artikel zurückgeben möchten?",
      "Approve order": "Bestellung genehmigen",
      "I agree with the Terms and Conditions": "Ich stimme den Nutzungsbedingungen zu",
      "No partial deliveries": "Keine Teillieferungen",
      "Return #": 'Return #',
      "ReturnDate": 'ReturnDate'
    },

    French: {
      "Username": "Nom d'utilisateur",
      "Password": 'Mot de passe',
      "ConfirmPassword": 'Confirmez le mot de passe',
      "Forgot_password": 'Oublié  Mot de passe?',
      "Sign_in": "S'identifierg",
      "Orders": 'Commandes',
      "Dashboard": 'Tableau de bord',
      "Sales_No": 'Ventes No',
      "Previous":'Précédent',
      "Next":'Suivant',
      "Show_entries":'Afficher entrées ',
      "Show":'Afficher',
      "Entries":'entrées',
      "Show_page":'Afficher page ',
      "PO_No": 'PO_No',
      "Order_Date": 'Commande Date',
      "Shipping_Date": 'livraison Date',
      "Total": 'Total',
      "Currency": 'Devise',
      "Status": 'Statute',
      "Download": 'Télécharger',
      "Past_Due": 'Passé  Du',
      "Due_Soon": 'Du  Bientôt',
      "Total_Outstanding": 'Total Exceptionnel',
      "Place_an_order": 'Endroit un commande',
      "Search_Lines": 'ChercherLignes',
      "Make_a_Payment": 'Faire une Paiement',
      "Credit_card": 'Crédit carte',
      "Last_5_Orders": 'Dernier 5 Ordres',
      "Next_5_Deliveries_Due": 'Prochain 5 Livraisons Du',
      "Outstanding_Payments": 'Exceptionnel Paiements',
      "Sales_Number": 'Ventes Nombre',
      "Delivery_Number": 'Livraison Nombre',
      "Due_Date": 'Du Date',
      "Invoice_Number": "Facture d'achat Nombre",
      "Amount": 'Montant',
      "Enter_email": 'Entrer email',
      "Back_to_Sign_in": 'Retour à Signe dans',
      "Next_Step": 'Prochain Étape',
      "New_Password": 'Nouveau Mot de passe',
      "Confirm_Password": 'Confirmer Mot de passe',
      "Item_Name": 'Article Nom',
      "Description": 'La description',
      "Quantity": 'Quantité',
      "Shipped_Quantity": 'Expédié Quantité',
      "Price": 'Prix',
      "Requested_Delivery_Date": 'Demandé Livraison Date',
      "PO_Reference": 'Po Reference',
      "Billing_Address": 'Facturation Adresse',
      "Shipping_Address": 'Expédition Adresse',
      "Order_Comments": 'Commande Comments',
      "Product": 'Produit',
      "Item_Price": 'Article Prix',
      "Line_Total": 'Ligne Total',
      "Click_to_make_new_row": 'Cliquez à faire Nouveau rangée',
      "Search": 'Chercher',
      "Submit_Order": 'Soumettre Commande',
      "Make_a_payment": 'Faire une Paiement',
      "Make_Payment": 'Faire Paiement',
      "Play": 'Jouer',
      "Type": 'Type',
      "Documet_Date": 'Document Date',
      "Invoice_No": "Facture d'achat  No",
      "Business_partner": 'Affaires partenaire',
      "Contact": 'Contact',
      "Ordertype": 'Commandetype',
      "Unit": 'Unité',
      "Delivery": 'Livraison #',
      "DeliveryDate": 'LivraisonDate',
      "Pay": 'Payer',
      "Collection": 'Collection',
      "Your_order_reference": 'Votre reférence de commande',
      "Invoice": "Facture d'achat",
      "Invoice #": "Facture d'achat #",
      "InvoiceDate": 'RechnungDate',
      "OrderNumber": 'CommandeNombre',
      "Batch": 'Lot',
      "Invoices": 'Factures',
      "CreditNotNo": 'Crédit no dog Non',
      "DateCreated": 'Date Créé',
      "Balance": 'Équilibre',
      "Applied_by": 'Appliqué par',
      "Place_sample_order": 'Musterbestellung aufgeben',
      "Save": 'Sauvegarder',
      "Collection_or_historical_orders": 'Collection ou commandes historiques',
      "Action": 'Action',
      "Product_code": 'Code produit',
      "Jobs": 'Travaux',
      "Length_specified": 'Longueur spécifiée',
      "Length_calculated": 'Longueur calculé',
      "Pattern": 'Modèle',
      "Order_rule": 'Ordre Règle',
      "Add_stroke": 'Ajouter Coup',
      "Remove_stroke": 'Retirer Coup',
      "Calculate_pattern_length": 'Calculer modèle longueur',
      "Processing": 'En traitement',
      "Cancel": 'Annuler',
      "Verspringend": 'Verspringend',
      "Accept_delivery": "J'accepte Livraison",
      "No_partial_deliveries": 'Non Partiel Livraisons',
      "Go_back_to_the_order": 'Revenir à la commande',
      "Resume": 'Reprendre',
      "Allowance": 'Allocation',
      "Product_image": 'Produit image',
      "Email": 'Email',
      "Sign_up": "S'inscrire",
      "have_an_account": "Vous n'avez pas de compte?",
      "User": 'Utilisatrice',
      "Users": 'Utilisatrices',
      "Add_User": 'Ajouter un utilisateur',
      "UserName": "Nom d'utilisateur",
      "PhoneNumber": "Numéro de téléphone",
      "Active": 'Active',
      "Result_on_page": "Résultat sur la page",
      "Results_of": 'Resultats de',
      "Delete": 'Supprimer',
      "Edit": "Éditer",
      "Roles": "Les rôles",
      "UserCode": "Code d'utilisateur",
      "CustomerCode": 'Code client',
      "FirstName": 'Prénom',
      "LastName": 'Nom de famille',
      "keep_logged_in": "Rester connecté",
      "have_account": "Je n'ai pas de compte",
      "Add_order": 'Ajouter une commande',
      "ItemCode": "Code de l'article",
      "ItemDescription": "Description de l'objet",
      "DocNum": 'DocNum',
      "DocDate": 'DocDate',
      "cardName": 'Nom de la carte',
      "dbsCollection": 'dbsCollection',
      "Filter": 'Filtre',
      "Quick_search": 'Rapide Chercher',
      "Add_filter": 'Ajouter un filtre',
      "Deliveries": 'Livraisons',
      "Salesinvoices": 'Factures des ventes',
      "DocTotal": 'DocTotal',
      "Deactivate": 'Désactiver',
      "Returns": 'Retour',
      "Edit_User": "Modifier l'utilisateur",
      "Test": 'Tester',
      "Login As": "Se connecter en tant que",
      "Go_Back_Admin": 'Retour administrateur',
      "Customer_reference": 'Référence client',
      "City_Country": 'Ville Pays',
      "Street": 'rue',
      "Product_description": 'Description du produit',
      "Image": 'Image',
      "Expected_deliver_week": 'Semaine de livraison prévue',
      "Order": 'Ordre #',
      "Language": 'Langue',
      "Search_Item": "Rechercher un élément",
      "Add_to_order": 'Ajouter à la commande',
      "Orderline": 'Order look like',
      "Staggered": 'Décalé',
      "Rows": 'Lignes',
      "Row_length": 'Longueur de ligne',
      "Row_length_calculated": 'Rangée longueur calculé',
      "Total_row_length": 'Total rangée longueur',
      "Total_lengh": 'Total longueur',
      "Add_to_row": 'Ajouter à la ligne',
      "Pattern_calculation": 'Calculate the model',
      "Date": 'Date',
      "DocDueDate": 'DocDueDate',
      "OrderSummary": 'Ordre Sommaire',
      "Profile": 'Profil',
      "ResetPassword": 'Réinitialiser Mot de passe',
      "Logout": 'Se déconnecter',
      "CustomerName": 'CustomerName',
      "ShowPrice": 'Afficher le prix',
      "Return details": 'Détails de retour',
      "Salesinvoice details": 'Détails de la facture de vente',
      "Delivery details": 'Détails de livraison',
      "NoPatternCalculation": 'Aucun calcul de modèle',
      "Pattern calculation needs to be filled for this product, do you want to delete the product from the order lines?": "Le calcul du modèle doit être rempli pour ce produit, voulez-vous supprimer le produit des lignes de commande?",
      "Zipcode": "Zipcode",
      "City": "Ville",
      "StreetNo": "Rue non",
      "News": "Nouvelles",
      "Add News": "Ajouter des nouvelles",
      "Subject Dutch": "MatièreNéerlandais",
      "Subject English": "Sujet anglais",
      "Subject German": "Sujet allemand",
      "Subject French": "Sujet Française",
      "Text Dutch": "Texte Nederlands",
      "Text English": "Texte Engels",
      "Text German": "Texte Duits",
      "Text French": 'Texte Frans',
      "StartDate": "Date de début",
      "EndDate": "Date de fin",
      "Are you sure to do this?": "Êtes-vous sûr de faire cela?",
      "View": "Vue",
      "Edit News": "Éditer Nouvelles",
      "View News": "Vue Nouvelles",
      "Are you sure that you want to return this item?": "Êtes-vous sûr de vouloir retourner cet article?",
      "Approve order": "Approuver la commande",
      "I agree with the Terms and Conditions": "J'accepte les termes et conditions",
      "No partial deliveries": "Pas de livraisons partielles",
      "Return #": 'Return #',
      "ReturnDate": 'ReturnDate'
    }
  };