export const TRANSLATIONS = {
    en_US: {
      Username: 'Username',
      Password: 'Password',
      ConfirmPassword: 'ConfirmPassword',
      Forgot_password: 'Forgot password?',
      Sign_in: 'Login',
      Orders: 'Orders',
      Dashboard: 'Dashboard',
      Sales_No: 'Sales No',
      Previous:'Previous',
      Next:'Next',
      Show_entries:'Show entries',
      Show:'Show',
      Entries:'entries',
      Show_page:'Showing page',
      PO_No: 'PO_No',
      Order_Date: 'OrderDate',
      Shipping_Date: "ShippingDate",
      Total: 'Total',
      Currency: 'Currency',
      Status: 'Status',
      Download: 'Download',
      Past_Due: 'Past Due',
      Due_Soon: 'Due Soon',
      Total_Outstanding: 'Total Outstanding',
      Place_an_order: 'Place an order',
      Search_Lines: 'Search Products and Create Order Lines',
      Make_a_Payment: 'Make a Payment',
      Credit_card: 'Credit card, PayPal, Worldpay, On Account',
      Last_5_Orders: 'Last 5 Orders',
      Next_5_Deliveries_Due: 'Next 5 Deliveries Due',
      Outstanding_Payments: 'Outstanding Payments',
      Sales_Number: 'Sales Number',
      Delivery_Number: 'Delivery Number',
      Due_Date: 'Due Date',
      Invoice_Number: 'Invoice Number',
      Amount: 'Amount',
      Enter_email: 'EnterEmail',
      Back_to_Sign_in: 'Back to Sign in',
      Next_Step: 'Next Step',
      New_Password: 'NewPassword',
      Confirm_Password: 'ConfirmPassword',
      Item_Name: 'ItemName',
      Description: 'Description',
      Quantity: 'Quantity',
      Shipped_Quantity: 'ShippedQuantity',
      Price: 'Price',
      Requested_Delivery_Date: 'Requested Delivery Date',
      PO_Reference: 'PO Reference',
      Billing_Address: 'Billing Address',
      Shipping_Address: 'Shipping Address',
      Order_Comments: 'Order Comments',
      Product: 'Product',
      Item_Price: 'ItemPrice',
      Line_Total: 'Line Total',
      Click_to_make_new_row: 'Click to make new row',
      Search: 'Search',
      Submit_Order: 'Submit Order',
      Make_a_payment: 'Make a payment',
      Make_Payment: 'Make Payment',
      Play: 'Play',
      Type: 'Type',
      Documet_Date: 'DocumentDate',
      Invoice_No: 'Invoice No',
      Business_partner: 'Business partner',
      Contact: 'Contact',
      Ordertype: 'Ordertype',
      Unit: 'Unit',
      DeliveryDate: 'DeliveryDate',
      Pay: 'Pay',
      Collection: 'Collection',
      Your_order_reference: 'Your order reference',
      Invoice: 'Invoice',
      InvoiceDate: 'InvoiceDate',
      OrderNumber: 'OrderNumber',
      Batch: 'Batch',
      Invoices: 'Invoices',
      CreditNotNo: 'Credit Note NO',
      DateCreated: 'Date Created',
      Balance: 'Balance',
      Applied_by: 'Applied by',
      Place_sample_order: 'Place sample order',
      Save: 'Save',
      Collection_or_historical_orders: 'Collection or historical orders',
      Action: 'Action',
      Product_code: 'Product code',
      Jobs: 'Jobs',
      Length_specified: 'Length specified',
      Length_calculated: 'Length calculated',
      Pattern: 'Pattern',
      Order_rule: 'Order rule',
      Add_stroke: 'Add stroke',
      Remove_stroke: 'Remove stroke',
      Calculate_pattern_length: 'Calculate pattern length',
      Processing: 'Processing',
      Cancel: 'Cancel',
      Verspringend: 'verspringend',
      Accept_delivery: 'Accept Delivery',
      No_partial_deliveries: 'No partial deliveries',
      Go_back_to_the_order: 'Go back to the order',
      Resume: 'Resume',
      Allowance: 'Allowance',
      Product_image: 'Product image',
      Email: 'Email',
      Sign_up: 'Sign up',
      have_an_account: "Don't have an account?",
      User: 'User',
      Users: 'Users',
      Add_User: 'Add User',
      UserName: 'UserName',
      PhoneNumber: 'PhoneNumber',
      Active: 'Active',
      Result_on_page: 'result on page',
      Results_of: 'results of',
      Delete: 'Delete',
      Edit: 'Edit',
      Roles: 'Role',
      UserCode: 'UserCode',
      CustomerCode: 'CustomerCode',
      FirstName: 'FirstName',
      LastName: 'LastName',
      keep_logged_in: 'Keep me logged in',
      have_account: "Don't have account",
      Add_order: 'Add Order',
      ItemCode: 'ItemCode',
      ItemDescription: 'ItemDescription',
      DocNum: 'DocNum',
      DocDate: 'DocDate',
      cardName: 'cardName',
      dbsCollection: 'dbsCollection',
      Filter: 'Filter',
      Quick_search: 'Quick_search',
      Add_filter: 'Add filter',
      Deliveries: 'Deliveries',
      Salesinvoices: 'Salesinvoices',
      DocTotal: 'DocTotal',
      Deactivate: 'Deactivate',
      Returns: 'Returns'
    },

    nl_BE: {
      Username: 'Gebruikersnaam',
      Password: 'Wachtwoord',
      ConfirmPassword: 'Bevestig wachtwoord',
      Forgot_password: 'Wachtwoord vergeten?',
      Sign_in: 'Aanmelden',
      Orders: 'Vestellen',
      Dashboard: 'Dashboard',
      Sales_No: 'Verkoop No',
      Previous:'Vorige',
      Next:'Volgende',
      Show_entries:'Toon records',
      Show:'Toon',
      Entries:'Records',
      Show_page:'Pagina weergeven',
      PO_No: 'PO_No',
      Order_Date: 'BestellenDatum',
      Shipping_Date: 'VerzendingDatum',
      Total: 'Totaal',
      Currency: 'Valuta',
      Status: 'Toestand',
      Download: 'Download',
      Past_Due: 'Verleden Due',
      Due_Soon: 'Due Spoedig',
      Total_Outstanding: 'Totaal Voortreffelijk',
      Place_an_order: 'Een bestelling plaatsen',
      Search_Lines: 'Zoek producten en maak orderregels',
      Make_a_Payment: 'Maak een betaling',
      Credit_card: 'Creditcard, PayPal, Worldpay, op account',
      Last_5_Orders: 'Laatste 5 bestellingen',
      Next_5_Deliveries_Due: 'Volgende 5 Leveringen verschuldigd',
      Outstanding_Payments: 'Openstaande betalingen',
      Sales_Number: 'Verkoop Aantal',
      Delivery_Number: 'Levering Aantal',
      Due_Date: 'Due Datum',
      Invoice_Number: 'Factuur Aantal',
      Amount: 'Bedrag',
      Enter_email: 'InvoerenEmail',
      Back_to_Sign_in: 'Terug naar inloggen',
      Next_Step: 'Volgende Stap',
      New_Password: 'Nieuw Wachtwoord',
      Confirm_Password: 'Bevestigen Wachtwoord',
      Item_Name: 'ItemNaam',
      Description: 'Beschrijving',
      Quantity: 'Aantal',
      Shipped_Quantity: 'Verunden Aantal',
      Price: 'Prijs',
      Requested_Delivery_Date: 'Gevraagde afleverdatum',
      PO_Reference: 'Po Referenie',
      Billing_Address: 'Factuur Adres',
      Shipping_Address: 'Verzending  Adres',
      Order_Comments: 'Bestellen Comments',
      Product: 'Product',
      Item_Price: 'ItemPrijs',
      Line_Total: 'Lijn Totaal',
      Click_to_make_new_row: 'Click om een ​​nieuwe rij te maken',
      Search: 'Zoeken',
      Submit_Order: 'Voorleggen Bestellen',
      Make_a_payment: 'Maken een betaling',
      Make_Payment: 'Maken Betaling',
      Play: 'Speel',
      Type: 'Type',
      Documet_Date: 'DocumentDatum',
      Invoice_No: 'Factuur No',
      Business_partner: 'Bedrijf partner',
      Contact: 'Contact',
      Ordertype: 'Bestellentype',
      Unit: 'Eenheid',
      DeliveryDate: 'LeveringDatum',
      Pay: 'Betalen',
      Collection: 'Verzameling',
      Your_order_reference: 'Votre reférence de commande',
      Invoice: 'Factuur',
      InvoiceDate: 'FactuurDatum',
      OrderNumber: 'BestellenNummer',
      Batch: 'Partij',
      Invoices: 'Facturen',
      CreditNotNo: 'Credit Niet Nee',
      DateCreated: 'Datum gemaakt',
      Balance: 'Balance',
      Applied_by: 'Aangebracht door',
      Place_sample_order: 'Plaats monster bestelling',
      Save: 'Obslaan',
      Collection_or_historical_orders: 'Verzameling of historische bestellingen',
      Action: 'Actie',
      Product_code: 'Product code',
      Jobs: 'Banen',
      Length_specified: 'Lengte opgegeven',
      Length_calculated: 'Lengte berekend',
      Pattern: 'Patrron',
      Order_rule: 'Orderrege',
      Add_stroke: 'Toevoegen  beroerte',
      Remove_stroke: 'Verwijderen beroerte',
      Calculate_pattern_length: 'Bereken patroonlengte',
      Processing: 'Verwerken',
      Cancel: 'Annuleren',
      Verspringend: 'Verspringend',
      Accept_delivery: 'Levering accepteren',
      No_partial_deliveries: 'Geen gedeeltelijke leveringen',
      Go_back_to_the_order: 'Ga terug naar de bestelling',
      Resume: 'Hervat',
      Allowance: 'Toelage',
      Product_image: 'Product afbeelding',
      Email: 'E-mail',
      Sign_up: 'Inschrijven',
      have_an_account: "Heb je geen account?",
      User: 'Gebruiker',
      Users: 'Gebruikers',
      Add_User: 'Voeg gebruiker toe',
      UserName: 'Gebruikersnaam',
      PhoneNumber: 'Telefoonnummer',
      Active: 'Actief',
      Result_on_page: 'Resultaten op pagine',
      Results_of: 'resultaten van',
      Delete: 'Verwijderen',
      Edit: 'Bewerk',
      Role: 'Rol',
      UserCode: 'GebruikerCode',
      CustomerCode: 'klantCode',
      FirstName: 'EersteNaam',
      LastName: 'LaatsteName',
      keep_logged_in: 'Ik wil ingelogd blijven',
      have_account: "Heb geen account",
      Add_order: 'Toevoegen Bestellen',
      ItemCode: 'Artikelcode',
      ItemDescription: 'ItemBeschrijving',
      DocNum: 'DocNum',
      DocDate: 'DocDatum',
      cardName: 'kaartNaam',
      dbsCollection: 'dbsCollectie',
      Filter: 'Filter',
      Quick_search: 'Snel zoeken',
      Add_filter: 'Toevoegen filter',
      Deliveries: 'Leveringen',
      Salesinvoices: 'Verkoopfacturen',
      DocTotal: 'DocTotaal',
      Deactive: 'deactiveren',
      Returns: 'Geeftterug'
    },
    
    de_DE: {
      Username: 'Nutzername',
      Password: 'Passwort',
      ConfirmPassword: 'Bevestig wachtwoord',
      Forgot_password: 'Vergessen Passwort',
      Sign_in: 'Einloggen',
      Orders: 'Aufträge',
      Dashboard: 'Instrumententafel',
      Sales_No: 'Vertrieb Nein',
      Previous:'Bisherige',
      Next:'Nächster',
      Show_entries:'Show Einträge',
      Show:'Show',
      Entries:'Einträge',
      Show_page:'Show Seite',
      PO_No: 'PO_No',
      Order_Date: 'Bestellung Date',
      Shipping_Date: 'Versand Date',
      Total: 'Gesamt',
      Currency: 'Währung',
      Status: 'Status',
      Download: 'Herunterladen',
      Past_Due: 'Vergangenheit Fällig',
      Due_Soon: 'Fällig Bald',
      Total_Outstanding: 'Gesamt Hervorragend',
      Place_an_order: 'Ort ein bestellen',
      Search_Lines: 'Suche Linien',
      Make_a_Payment: 'Machen ein Zahlung',
      Credit_card: 'Anerkennung Karte',
      Last_5_Orders: 'Zuletzt 5 Aufträge',
      Next_5_Deliveries_Due: 'Nächster 5 Lieferungen Fällig',
      Outstanding_Payments: 'Hervorragend Zahlungen',
      Sales_Number: 'Der Umsatz Nummer',
      Delivery_Number: 'Lieferung Nummer',
      Due_Date: 'Fällig Datum',
      Invoice_Number: 'Rechnung Nummer',
      Amount: 'Menge',
      Enter_email: 'Eingeben Email',
      Back_to_Sign_in: 'Zurück zu Zeichen ',
      Next_Step: 'Nächster Schritt',
      New_Password: 'Neu Passwort',
      Confirm_Password: 'Bestätigen Passwort',
      Item_Name: 'Article Name',
      Description: 'Beschreibung',
      Quantity: 'Menge',
      Shipped_Quantity: 'Versand erfolgt Menge',
      Price: 'Preis',
      Requested_Delivery_Date: 'Angefordert Lieferung Datum',
      PO_Reference: 'Po Referenz',
      Billing_Address: 'Abrechnung Addresses',
      Shipping_Address: 'Versand Addresses',
      Order_Comments: 'Bestellung Bemerkungen',
      Product: 'Product',
      Item_Price: 'Item Preis',
      Line_Total: 'Linie Gesamt',
      Click_to_make_new_row: 'Klicken zu machen Neu Reihe',
      Search: 'Suche',
      Submit_Order: 'Einreichen  Bestellung',
      Make_a_payment: 'Machen ein Zahlung',
      Make_Payment: 'Machen Zahlung',
      Play: 'Abspielen',
      Type: 'Art',
      Documet_Date: 'Dokumentieren Datum',
      Invoice_No: 'Rechnung Nein',
      Business_partner: 'Geschäft Partner',
      Contact: 'Kontakt',
      Ordertype: 'Auftragsart',
      Unit: 'Einheit',
      DeliveryDate: 'LieferungDatum',
      Pay: 'Zahlen',
      Collection: 'Sammlung',
      Your_order_reference: 'Ihre Bestellnummer',
      Invoice: 'Rechnung',
      InvoiceDate: 'RechnungDatum',
      OrderNumber: 'BestellungNummer',
      Batch: 'Stapel',
      Invoices: 'Rechnungen',
      CreditNotNo: 'Anerkennung Nicht Nein',
      DateCreated: 'Date erstellt',
      Balance: 'Balance',
      Applied_by: 'Durch Anwendung',
      Place_sample_order: "Passer la commande d'échantillon",
      Save: 'Speichern',
      Collection_or_historical_orders: 'Sammlung oder historische Ordnungen',
      Action: 'Aktion',
      Product_code: 'Product code',
      Email: 'Email',
      Sign_up: 'Anmelden',
      have_an_account: "Sie haben noch keinen Account?",
      User: 'Benutzerin',
      Users: 'Benutzer',
      Add_User: 'Ajouter un utilisateur',
      UserName: 'Nutzername',
      PhoneNumber: 'Telefonnummer',
      Active: 'Aktiv',
      Result_on_page: 'Ergebnis auf Seite',
      Results_of: 'ergebnisse von',
      Delete: 'Löschen',
      Edit: 'Bearbeiten',
      Roles: 'Rolle',
      UserCode: 'BenutzerCode',
      CustomerCode: 'KundeCode',
      FirstName: 'ZuerstName',
      LastName: 'ZuletztName'
    },

    fr_FR: {
      Username: "Nom d'utilisateur",
      Password: 'Mot de passe',
      ConfirmPassword: 'Confirmez le mot de passe',
      Forgot_password: 'Oublié  Mot de passe?',
      Sign_in: "S'identifierg",
      Orders: 'Commandes',
      Dashboard: 'Tableau de bord',
      Sales_No: 'Ventes No',
      Previous:'Précédent',
      Next:'Suivant',
      Show_entries:'Afficher entrées ',
      Show:'Afficher',
      Entries:'entrées',
      Show_page:'Afficher page ',
      PO_No: 'PO_No',
      Order_Date: 'Commande Date',
      Shipping_Date: 'livraison Date',
      Total: 'Total',
      Currency: 'Devise',
      Status: 'Statute',
      Download: 'Télécharger',
      Past_Due: 'Passé  Du',
      Due_Soon: 'Du  Bientôt',
      Total_Outstanding: 'Total Exceptionnel',
      Place_an_order: 'Endroit un commande',
      Search_Lines: 'ChercherLignes',
      Make_a_Payment: 'Faire une Paiement',
      Credit_card: 'Crédit carte',
      Last_5_Orders: 'Dernier 5 Ordres',
      Next_5_Deliveries_Due: 'Prochain 5 Livraisons Du',
      Outstanding_Payments: 'Exceptionnel Paiements',
      Sales_Number: 'Ventes Nombre',
      Delivery_Number: 'Livraison Nombre',
      Due_Date: 'Du Date',
      Invoice_Number: "Facture d'achat Nombre",
      Amount: 'Montant',
      Enter_email: 'Entrer email',
      Back_to_Sign_in: 'Retour à Signe dans',
      Next_Step: 'Prochain Étape',
      New_Password: 'Nouveau Mot de passe',
      Confirm_Password: 'Confirmer Mot de passe',
      Item_Name: 'Article Nom',
      Description: 'La description',
      Quantity: 'Quantité',
      Shipped_Quantity: 'Expédié Quantité',
      Price: 'Prix',
      Requested_Delivery_Date: 'Demandé Livraison Date',
      PO_Reference: 'Po Reference',
      Billing_Address: 'Facturation Adresse',
      Shipping_Address: 'Expédition Adresse',
      Order_Comments: 'Commande Comments',
      Product: 'Produit',
      Item_Price: 'Article Prix',
      Line_Total: 'Ligne Total',
      Click_to_make_new_row: 'Cliquez à faire Nouveau rangée',
      Search: 'Chercher',
      Submit_Order: 'Soumettre Commande',
      Make_a_payment: 'Faire une Paiement',
      Make_Payment: 'Faire Paiement',
      Play: 'Jouer',
      Type: 'Type',
      Documet_Date: 'Document Date',
      Invoice_No: "Facture d'achat  No",
      Business_partner: 'Affaires partenaire',
      Contact: 'Contact',
      Ordertype: 'Commandetype',
      Unit: 'Unité',
      DeliveryDate: 'LivraisonDate',
      Pay: 'Payer',
      Collection: 'Collection',
      Your_order_reference: 'Votre reférence de commande',
      Invoice: "Facture d'achat",
      InvoiceDate: 'RechnungDate',
      OrderNumber: 'CommandeNombre',
      Batch: 'Lot',
      Invoices: 'Factures',
      CreditNotNo: 'Crédit no dog Non',
      DateCreated: 'Date Créé',
      Balance: 'Équilibre',
      Applied_by: 'Appliqué par',
      Place_sample_order: 'Musterbestellung aufgeben',
      Save: 'Sauvegarder',
      Collection_or_historical_orders: 'Collection ou commandes historiques',
      Action: 'Action',
      Product_code: 'Code produit',
      Email: 'Email',
      Sign_up: "S'inscrire",
      have_an_account: "Vous n'avez pas de compte?",
      User: 'Utilisatrice',
      Users: 'Utilisatrices',
      UserName: "Nom d'utilisateur",
      PhoneNumber: "Numéro de téléphone",
      Active: 'Actif',
      Result_on_page: 'Résultat à la page',
      Results_of: 'resultats de',
      Delete: 'Supprimer',
      Edit: 'Éditer',
      Roles: 'Rôle',
      UserCode: 'UtilisateurCode',
      CustomerCode: 'ClientCode',
      FirstName: 'PremierNom',
      LastName: 'DernierName'
    }
  };